name: base
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - conda==24.9.0
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - menuinst
  - anaconda-anon-usage
    # - pytorch::pytorch
  - pytorch
    # - torchaudio
    # - torchvision
  - anaconda::scikit-learn
  - matplotlib
  - natsort
  - numpy
